"use client";

export const AVAILABLE_LANGUAGES = [
  { code: "en", label: "EN", name: "English", nativeName: "English", flag: "GB", popular: true },
  { code: "am", label: "AM", name: "Amharic", nativeName: "አማርኛ", flag: "ET" },
  { code: "ar", label: "AR", name: "Arabic", nativeName: "العربية", flag: "AE", popular: true },
  { code: "az", label: "AZ", name: "Azerbaijani", nativeName: "Azərbaycanca", flag: "AZ" },
  { code: "bn", label: "BN", name: "Bengali", nativeName: "বাংলা", flag: "BD" },
  { code: "bg", label: "BG", name: "Bulgarian", nativeName: "Български", flag: "BG" },
  { code: "my", label: "MY", name: "Burmese", nativeName: "မြန်မာ", flag: "MM" },
  { code: "zh", label: "ZH", name: "Chinese", nativeName: "中文", flag: "CN", popular: true },
  { code: "hr", label: "HR", name: "Croatian", nativeName: "Hrvatski", flag: "HR" },
  { code: "cs", label: "CS", name: "Czech", nativeName: "Čeština", flag: "CZ" },
  { code: "da", label: "DA", name: "Danish", nativeName: "Dansk", flag: "DK" },
  { code: "nl", label: "NL", name: "Dutch", nativeName: "Nederlands", flag: "NL" },
  { code: "et", label: "ET", name: "Estonian", nativeName: "Eesti", flag: "EE" },
  { code: "fr", label: "FR", name: "French", nativeName: "Français", flag: "FR", popular: true },
  { code: "ka", label: "KA", name: "Georgian", nativeName: "ქართული", flag: "GE" },
  { code: "de", label: "DE", name: "German", nativeName: "Deutsch", flag: "DE", popular: true },
  { code: "el", label: "EL", name: "Greek", nativeName: "Ελληνικά", flag: "GR" },
  { code: "hu", label: "HU", name: "Hungarian", nativeName: "Magyar", flag: "HU" },
  { code: "is", label: "IS", name: "Icelandic", nativeName: "Íslenska", flag: "IS" },
  { code: "id", label: "ID", name: "Indonesian", nativeName: "Bahasa Indonesia", flag: "ID" },
  { code: "it", label: "IT", name: "Italian", nativeName: "Italiano", flag: "IT" },
  { code: "ja", label: "JA", name: "Japanese", nativeName: "日本語", flag: "JP" },
  { code: "km", label: "KM", name: "Khmer", nativeName: "ខ្មែរ", flag: "KH" },
  { code: "ko", label: "KO", name: "Korean", nativeName: "한국어", flag: "KR" },
  { code: "lv", label: "LV", name: "Latvian", nativeName: "Latviešu", flag: "LV" },
  { code: "lt", label: "LT", name: "Lithuanian", nativeName: "Lietuvių", flag: "LT" },
  { code: "ms", label: "MS", name: "Malay", nativeName: "Bahasa Melayu", flag: "MY" },
  { code: "ne", label: "NE", name: "Nepali", nativeName: "नेपाली", flag: "NP" },
  { code: "no", label: "NO", name: "Norwegian", nativeName: "Norsk", flag: "NO" },
  { code: "fa", label: "FA", name: "Persian", nativeName: "فارسی", flag: "IR" },
  { code: "pl", label: "PL", name: "Polish", nativeName: "Polski", flag: "PL" },
  { code: "pt", label: "PT", name: "Portuguese", nativeName: "Português", flag: "PT", popular: true },
  { code: "ro", label: "RO", name: "Romanian", nativeName: "Română", flag: "RO" },
  { code: "ru", label: "RU", name: "Russian", nativeName: "Русский", flag: "RU", popular: true },
  { code: "sr", label: "SR", name: "Serbian", nativeName: "Српски", flag: "RS" },
  { code: "sk", label: "SK", name: "Slovak", nativeName: "Slovenčina", flag: "SK" },
  { code: "sl", label: "SL", name: "Slovene", nativeName: "Slovenščina", flag: "SI" },
  { code: "es", label: "ES", name: "Spanish", nativeName: "Español", flag: "ES", popular: true },
  { code: "th", label: "TH", name: "Thai", nativeName: "ไทย", flag: "TH" },
  { code: "tr", label: "TR", name: "Turkish", nativeName: "Türkçe", flag: "TR" },
  { code: "uk", label: "UK", name: "Ukrainian", nativeName: "Українська", flag: "UA" },
  { code: "uz", label: "UZ", name: "Uzbek", nativeName: "Oʻzbekcha", flag: "UZ" },
  { code: "vi", label: "VI", name: "Vietnamese", nativeName: "Tiếng Việt", flag: "VN" },
];

export const POPULAR_LANGUAGE_CODES = AVAILABLE_LANGUAGES.filter((lang) => lang.popular).map(
  (lang) => lang.code
);
